### ISSUE TITLE
mappability mask file

### ISSUE THREAD

**Issue by BegonaMartinez** [stschiff/msmc#10]
Dear author, 

I am starting to prepare the infiles for the analyses of MSMC and I have encountered a difficulty about the mappability_mask file. I am following the indications in Heng's Li SNPable regions web to generate my mask_35_50.fa file (as a starting point I am using the same parameters as Li). Otherwise I cannot see how to  transform this mask_35_50.fa file into your mappability_mask.chromosome.bed.txt.gz file. I wanted to have a look to the maks you made for humans in your ftp site as you indicate ("For humans (GRCh37), you can download these masks from my ftp site, see the readme for msmc") but I do not see where in the readme it is indicated how to access to this data 
Could you give me a hint?

Thanks a lot in advance. Best,

Begona

**Comment by stschiff** [comment]
Yes, indeed you need a little script to convert the mask from fast to bed format. I upload the script I use to the msmc-tools now. I hope that'll help.
