### ISSUE TITLE
Won't compile on 32-bit linux.

### ISSUE THREAD

**Issue by alanrogers** [stschiff/msmc#12]
Yesterday, on a 64-bit mac, I pulled msmc from github and compiled with no difficulty. Also works on a 64-bit linux box. But I can't compile on a 32-bit linux box. Details are below, I'd be grateful for any suggestions.

Thanks, Alan Rogers

msmc release on github: c50cfbe36a7b2ec5dfb4a84298497c98382a57ea

I edited Makefile as instructed, to reflect the location of my libraries. But this can't be the problem because I'm getting a compilation error, not a linkage error.

dmd version: DMD32 D Compiler v2.067.1

Beginning of error messages:

msmc.d(173): Error: cannot implicitly convert expression (reduce(timeSegmentPattern)) of type ulong to uint
msmc.d(272): Error: function maximization_step.getMaximization (double[] eVec, double[][] eMat, MSMCmodel params, const(uint[]) timeSegmentPattern, bool fixedPopSize, bool fixedRecombination) is not callable using argument types (double[], double[][], MSMCmodel, ulong[], bool, bool)
branchlength.d(129): Error: cannot implicitly convert expression (pos) of type ulong to uint
branchlength.d(154): Error: cannot append type Tuple!(ulong, double) to type Tuple!(uint, double)[]

**Comment by alanrogers** [comment]
The issue seems to be a conflict between the following two lines:
46: auto timeSegmentPattern = [1UL, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2];
61: size_t nrTimeSegments;

Line 46 defines timeSegmentPattern as an array of ulong values. In line 61, size_t is the same as ulong on 64-bit machines but is uint on 32-bit machines. In the latter case, line 173 attempts to assign a ulong value to a uint variable, generating an error.

**Comment by stschiff** [comment]
Thanks. That's annoying. I will try to fix it ASAP. Stephan

**Comment by stschiff** [comment]
Hi Alan, I can compile on both Mac and Linux without a problem. Please reopen this issue if you encounter Compilation problems. Thanks.
