### ISSUE TITLE
Doesn't multithread

### ISSUE THREAD

**Issue by alanrogers** [stschiff/msmc#13]
I'm running with following command line:

msmc -r 0.67 -t 20 -R -o 100g 100g.msmcin

According to the documentation, that should launch 20 threads, but according to the "top" linux command, msmc is only using 1.

**Comment by stschiff** [comment]
Multithreading is implemented in the expectation step for running on parallel on multiple regions (chromosomes). So if you just pass in one file (=one chromosome) it can't multithread.
