### ISSUE TITLE
Segmentation fault with large number of scaffolds

### ISSUE THREAD

**Issue by pelagial** [stschiff/msmc#15]
Hi Stephan,

I am running MSMC on a mammal with scaffold-level assembly. Unfortunately, the N50 is quite low and I have ~3500 scaffolds > 100kb, that I want to base my analyses on. On subsets of the data MSMC runs nicely, but on the whole dataset it crashes with Segmentation Fault during one of the first iterations after computing ~1000 scaffolds. This reflects about 1.5 Gb, so I don't think it is the amount of data itself. MSMC was run with default settings and 2 unphased haplotypes. 

Many thanks for any help!

Best, 
Fritjof

**Comment by stschiff** [comment]
Hmm. This isn’t the first time people report seg-faults. This should not happen, and I’d like to fix it. Can you send me the data, zipped, perhaps via wetransfer or Dropbox? Can you also send me the exact command line you used?

Cheers,
Stephan

**Comment by pelagial** [comment]
I uploaded the multihetsep files, including log and command line: https://www.dropbox.com/s/oiagssflqxn28mb/msmc_test_segfault.tgz?dl=0 Please let me know, if you need more.

Fritjof

**Comment by stschiff** [comment]
Hi Fritjof,

I found the problem. You have some empty input files. I added an assertion to test for that and to give a more useful error.

Best,
Stephan

**Comment by pelagial** [comment]
Indeed! I filtered for such files and now it works perfectly. Many thanks!
