### ISSUE TITLE
Gene flow estimation with 2 haplotypes?

### ISSUE THREAD

**Issue by arundurvasula** [stschiff/msmc#17]
Hi,

Is it possible to run msmc with the -P option where there are two haplotypes, each from a different subpopulation? It only seems to work so far with 4+ haplotypes.

Thanks!

**Comment by stschiff** [comment]
Hello Arun,

Yes, of course you can run it on 2+2 haplotypes. That’s the standard case for cross-population analysis, as shown for example in Figure 4 of our article (Schiffels and Durbin, 2014).

You would input a standard file with 4 haplotypes, and use „-P 0,0,1,1“ to denote the two subpopulations. You can also use an input file with more haplotypes and subselect some using the „-I“ option.

Stephan

P.S. Please note the new google-group on MSMC, CC’d.

**Comment by stschiff** [comment]
Hi Stephan,

Sorry, I was unclear. I meant 1+1 haplotypes where there are two total 
haplotypes in the input file, each one from a different subpopulation.

Thanks!
Arun

**Comment by stschiff** [comment]
In that case you can just run it as with a normal diploid individual and plot the inverse population size as coalescence rate. But you don’t get estimates for the coalescence rates within each population, so you cannot make the relative cross coalescence rate plot I have in the papers.
Your case is very similar to what in Li and Durbin was done with the haploid X chromosomes (the „pseudo-diploid“ individuals).

Stephan

**Comment by arundurvasula** [comment]
Okay, that makes sense. Thank you!
