### ISSUE TITLE
Questions of using MSMC decode on multiple haplotypes

### ISSUE THREAD

**Issue by muhuaw** [stschiff/msmc#19]
Hello Stephan,

Thank you for writing MSMC! It helps me to solve some important problems of my project. After using the default function of MSMC, 

I am trying to use the decode function to estimate tMRCA states for my samples. However, when I use a file that contains four haplotypes as input for MSMC decode, it just output 40 columns instead of 240 columns as described in the manual. I used this file as input for two other functions of MSMC and it worked perfectly. 

Here is a snapshot of my input file:
chrXV   711     293     TCCC
chrXV   1950    1063    TCCC
chrXV   2333    215     AGGG
chrXV   2410    31      CGCC
chrXV   2448    38      TCTT
chrXV   2838    267     TATT
chrXV   2863    25      TGTT
chrXV   3057    189     GAAA
chrXV   3159    96      CCTT
chrXV   3245    86      GAGG

Here is the command I used:
local/msmc/build/decode -m 0.0015 -r 0.0012 PAXB07_LITC_UP_356_chrXV.msmc.txt > PAXB07_LITC_UP_356_chrXV.tMRCA.decode.txt

Do I need to specify in the command line there are four haplotypes in the input file? I read the help for decode function, it seems the script would automatically recognize how many haplotypes in the input. Thank you for your help.

Best Regards,
Muhua

**Comment by stschiff** [comment]
Hi Muhua,

you are right, it seems I have implemented the decode script to output only the marginal state space, so the one that sums up the internal states per time interval. Indeed, the documentation says something different.
Do you actually want to see all the states, though? It gets kind of complicated to plot and analyse… But it’s not a problem to implement that way in principle. Perhaps I’ll include a flag if all internal states are needed or so.

Stephan

P.S. Please post on the mailing list as well, CC’d.

**Comment by muhuaw** [comment]
Hi Stephan,

Thank you for the quick reply. I used MSMC to analyze separation of my populations. After getting the result for whole genome cross coalescence rate, I was wondering if I can get the cross coalescence rate for each genomic region. That’s why I was trying to use MSMC decode. I know this is not a proper way to do that. But I just want to know if I can get some useful result from genome scan. 

Best Regards,
Muhua

**Comment by stschiff** [comment]
I see, OK, I leave this open as a feature request, and will let you know when it’s implemented.

Stephan

**Comment by stschiff** [comment]
Sorry, I have too many other points on my to-do list for MSMC and MSMC2 and will likely not implement this any time soon, so I'll close the issue.
