### ISSUE TITLE
resequencing data of non-model diploid organism

### ISSUE THREAD

**Issue by xier92** [stschiff/msmc#23]
I am working on the domestication of economic animal ,and resequencing lots of samples with low depth（about 5x）.I'm wondering whether it is working when I use the function of "Analyzing population separations" using the snp information from such low depth data.
I'm planning to use 2 species data with 5x coverage each to  generate inputfile.As I didn't see any information about the depth ,can you give me some suggestions on these?

Thanks!!

**Comment by stschiff** [comment]
Hi,

my default answer is that 5x is too low. You need at least 20x to resolve heterozygotes. I don’t know how bad it will be, though. I think you’d have to run simulations with high false negative rates to see what that does to the estimates. Sorry I can’t be more specific.

By the way, we have a mailing list if you want to ask the community:

https://groups.google.com/forum/#!forum/msmc-popgen <https://groups.google.com/forum/#!forum/msmc-popgen>

Best wishes,
Stephan

**Comment by xier92** [comment]
Thank you for your reply and the comendatory URL.
