### ISSUE TITLE
Deal unphased vcf

### ISSUE THREAD

**Issue by dzaccook** [stschiff/msmc#25]
Hi,
I have two populations and each include many individual, I do not know the relationship of each individual in corresponding population,  I had called SNP using GATK, but I can not phase the vcf. Can I generate multihetsep files to fed to MSMC  (just determine the population size) like this:
./generate_multihetsep.py \
 --mask=22_chr1_mask.bed.gz (population 1) \
 --mask=23_chr1_mask.bed.gz (population 1) \
--mask=24_chr1_mask.bed.gz (population 1) \
--mask=25_chr1_mask.bed.gz (population 1) \
 --mask=1_chr1_mask.bed.gz (population 2) \
 --mask=2_chr1_mask.bed.gz (population 2) \
--mask=3_chr1_mask.bed.gz (population 2) \
--mask=4_chr1_mask.bed.gz (population 2) \
 --mask=chr1.mask.bed.gz \
 22_chr1.vcf.gz \
23_chr1.vcf.gz \
24_chr1.vcf.gz \
25_chr1.vcf.gz \
1_chr1.vcf.gz \
2_chr1.vcf.gz \
3_chr1.vcf.gz \
4_chr1.vcf.gz >multihetsep.txt,
or any idea?
Thank you!

**Comment by stschiff** [comment]
Hi, you have to phase, MSMC does not work on unphased data.
The command line you input is correct in principle, but if the VCFs are not phased, the output will be hard to interpret.
The other point here is that you are using way too many samples. You should first try one phased diploid from each population, then two from each at most. Eight individuals is the absolute maximum that I have ever run, but it takes excessive memory and requires even better phasing. Please try 2 phased diploids first!
Stephan

**Comment by dzaccook** [comment]
Thank you very much!

**Comment by stschiff** [comment]
If you have just one sample you don't need to phase.
