### ISSUE TITLE
remove repeatmask region

### ISSUE THREAD

**Issue by wlz0726** [stschiff/msmc#26]
Hi Stephan, 

I'm wondering if the results make sense when I **remove repeatmask region** to reduce the memory consumption and running time. I mainly want to estimate the relative cross coalescence rate. The results changed a little bit the postion of  rccr=0.5.

test plot: masked (orange) vs default (green)
![image](http://ofr9vioug.bkt.clouddn.com/QQ20161227-0.png?imageView/2/w/500)

best
lizhong

**Comment by stschiff** [comment]
Dear Lizhong,

if you have followed my recommended processing, you should have used a mappability mask that should have masked out repeat-regions anyway. 

Stephan

**Comment by wlz0726** [comment]
Thanks for your reply.
