### ISSUE TITLE
Can I use only sequence data in fasta format to run MSMC?

### ISSUE THREAD

**Issue by YangChaoCN** [stschiff/msmc#27]
Hello Stephan,

I am wondering that can I run MSMC with only know the sequence in fasta format, without any other information?

If yes, could you please give me some tips?

Thanks!

Best Regards,
Yangchao

**Comment by stschiff** [comment]
Hi Yangchao. You need diploid genotype calls. If your fasta sequence supports that, you could probably convert it to the input format for MSMC, but I have no script or such to support it. You could write to our mailing list and ask whether someone has a script:

https://groups.google.com/forum/#!forum/msmc-popgen <https://groups.google.com/forum/#!forum/msmc-popgen>

Stephan
