### ISSUE TITLE
Segmentation fault for running barley sample

### ISSUE THREAD

**Issue by lilei1** [stschiff/msmc#28]
Hi, Stephan.
I am running msmc for half of the chromosome 1 for barley sample, but got "Segmentation fault".
Since Barley is the selfing species,  I merged two bam files from different populations into single one and call SNPs with bamCaller.py, and used generate_multihetsep.py to create the [input file](https://github.com/lilei1/Notes/blob/master/B1K_WBDC355_msmc_input.txt) for msmc.

The command I used to run msmc is:
```
/panfs/roc/groups/9/morrellp/llei/software/msmc-1.0.0/build/msmc --timeSegmentPattern=5*4+25*2+5*4 -o /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_output.txt /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_input.txt
```
The error file looks like this:
```
read 623233 SNPs from file /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_input.txt
estimating scaled mutation rate: 0.00282695
input files:         ["/panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_input.txt"]
maxIterations:       20
mutationRate:        0.00282695
recombinationRate:   0.000706738
subpopLabels:        [0, 0]
timeSegmentPattern:  [4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4]
nrThreads:           24
nrTtotSegments:      90
verbose:             false
outFilePrefix:       /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_output.txt
naiveImplementation: false
hmmStrideWidth:      1000
fixedPopSize:        false
fixedRecombination:  false
initialLambdaVec:    []
directedEmissions:   false
skipAmbiguous:       false
indices:             [0, 1]
logging information written to /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_output.txt.log
loop information written to /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_output.txt.loop.txt
final results written to /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_output.txt.final.txt
[1/20] Baumwelch iteration
^M  * [1/1] Expectation Step/var/spool/torque/mom_priv/jobs/3836766.mesabim3.msi.umn.edu.SC: line 1: 10951 Segmentation fault      /panfs/roc/groups/9/morrellp/llei/software/msmc-1.0.0/build/msmc --timeSegmentPattern=5*4+25*2+5*4 -o /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_output.txt /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_input.txt
```
Do you have any idea what the problem is?

Thanks.
Best,
Li

**Comment by stschiff** [comment]
Hi,

it seems you have input only a single chromosome. This is like way too little data for running MSMC. What you are seeing is a consequence of extreme overfitting. If you want to try on a single chromosome, you need to sharply reduce the number of time segments, e.g. try “-p 10*1” for a start, or so. Also, have you changed the number of nrTtotSegments? Why is it 90 as in your log output below?

Stephan

**Comment by lilei1** [comment]
Thank you, Stephan.
I used bigger chunk of chromosome in chr1H of Barley and tried “-p 10*1”. This time, I did not get the  "Segmentation fault"; instead, I've got other error:

```
core.exception.AssertError@model/data.d(263): [623233, 9928, 312792352]
----------------
??:? [0x4ba661]
??:? [0x419d95]
??:? [0x4724e7]
??:? [0x470c20]
??:? [0x4706ab]
??:? [0x4bc0d6]
??:? [0x4bc020]
??:? [0x4bc092]
??:? [0x4bc020]
??:? [0x4bbf9e]
??:? [0x47efbd]
??:? __libc_start_main [0xca41ed1c]
```
Here is the  [input file](https://raw.githubusercontent.com/lilei1/Notes/master/sorted_B1K_WBDC355_chr1-3H_msmc_input.txt) and the command line I used is as below:

```bash
msmc --timeSegmentPattern=10*1 -o /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_msmc_output.txt /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_chr1-3H_msmc_input.txt
```
By the way, I did not use any additional mask file to generate the input file. I don't know if that is the issues. Any idea about this error?

Thanks.
Li

**Comment by stschiff** [comment]
This error suggests that your input file is invalid. Specifically, you seem to have two rows with the same position.
Stephan

**Comment by lilei1** [comment]
Hi, Stephan.
Thank you. I reproduced my input files: [chr1H](https://github.com/lilei1/Notes/blob/master/B1K_WBDC355_1H_msmc_input.txt) and [chr3H] (https://github.com/lilei1/Notes/blob/master/B1K_WBDC355_3H_msmc_input.txt), but still get the segmentation errors:
```shall
read 999726 SNPs from file /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1H_msmc_input.txt
read 1181541 SNPs from file /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_3H_msmc_input.txt
estimating scaled mutation rate: 0.00326317
input files:         ["/panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1H_msmc_input.txt", "/panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_3H_msmc_input.txt"]
maxIterations:       20
mutationRate:        0.00326317
recombinationRate:   0.000815793
subpopLabels:        [0, 0]
timeSegmentPattern:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
nrThreads:           24
nrTtotSegments:      10
verbose:             false
outFilePrefix:       /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1-3H_msmc_output.txt
naiveImplementation: false
hmmStrideWidth:      1000
fixedPopSize:        false
fixedRecombination:  false
initialLambdaVec:    []
directedEmissions:   false
skipAmbiguous:       false
indices:             [0, 1]
logging information written to /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1-3H_msmc_output.txt.log
loop information written to /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1-3H_msmc_output.txt.loop.txt
final results written to /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1-3H_msmc_output.txt.final.txt
[1/20] Baumwelch iteration
^M  * [1/2] Expectation Step^M  * [2/2] Expectation Step/var/spool/torque/mom_priv/jobs/4141119.mesabim3.msi.umn.edu.SC: line 1: 21045 Segmentation fault      /panfs/roc/groups/9/morrellp/llei/software/msmc-1.0.0/build/msmc --timeSegmentPattern=10*1 -o /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1-3H_msmc_output.txt /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1H_msmc_input.txt /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_3H_msmc_input.txt
```
Here is the command line I used:
```
msmc --timeSegmentPattern=10*1 -o /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1-3H_msmc_output.txt /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_1H_msmc_input.txt /panfs/roc/groups/9/morrellp/llei/Inversion/msmc/B1K_WBDC355_3H_msmc_input.txt
```
Do you have any idea about this?
Thanks.
Best,
Li

**Comment by stschiff** [comment]
Hi,

the short answer is that you’ve hit ab extremely low population size in the maximisation step which blows up some of the equations. The long answer is that I will probably have to implement boundaries on the inferred coalescence rates to avoid these nasty crashes in the future, but that is unfortunately a bit of more work than I have right now. I’ve made a note to improve this at some point.

Often, what causes extreme run-away effects in the fitting are somewhat too few data. Here you have a decent number of SNPs though, so I don’t know exactly what’s causing this…

Another note, I saw that you are running on 24 cores. That is unnecessary, as the only parallelisation that is going on is over the number of chromosomes you’re inputting. So since you’re only inputting two chromosomes, the most cores you need are 2. You can control that with the “-t 2” option.

Best,
Stephan

**Comment by stschiff** [comment]
I have now built in an option to artificially constrain the coalescence rates, see release 1.1.0, with options --loBoundLambda and --hiBoundLambda. Lambda is the scaled coalescence rate, with typical values around 1000 or so (it's on average around 2/theta, where theta is the heterozygosity), so you could try setting a lower bound of 10, and an upper bound of 1e6 or so, and see whether that fixes the issue in your case.
