### ISSUE TITLE
How to interpret the abormal results using two haplotypes from each population when running MSMC?

### ISSUE THREAD

**Issue by biozzq** [stschiff/msmc#30]
Dear @stschiff 

According to your previous suggestion, MSMC will have a better performance on population split  history than MSMC2. I ran MSMC analysis of two genomes (four haploid genomes) selected from each of the two populations with deeply sequenced and found all my rCCR never reach 1 (Figure 1). When I just ran analysis of one genome (two haploid genomes) for each population, although the rCCR reached to 1,  the rCCR drops from 0.5 to 0 instantaneously (Figure 2). I have never seen this phenomenon in other studies, hope you can give us some advice.  Thanks for your time.

This analyses only includes the relatively "pure" and deeply individuals (according to ADMIXTURE results), is this right?
![image](https://user-images.githubusercontent.com/15704257/28743372-f13d3eec-747a-11e7-8751-afb9928ac773.png)
Figure 1 four haplotypes from each population
![image](https://user-images.githubusercontent.com/15704257/28743376-04b11eb2-747b-11e7-8ec5-e791ff532595.png)
Figure 2, two haplotypes from each population

Best
Zhuqing

**Comment by stschiff** [comment]
I'm afraid I can't easily support interpreting MSMC results this way. I would need to know a lot more about the data to do that. Note that MSMC2 is now fully robust to cross-pop analysis, and I recommend it over MSMC.
