### ISSUE TITLE
msmc error

### ISSUE THREAD

**Issue by yuntwang** [stschiff/msmc#32]
Hi,
@stschiff 
I use the msmc2 infer population size history and meet an error.

**The command line:
msmc2  -t 5 --fixedRecombination -o msmc_result KB317697.1.multihetsep.txt KB317698.1.multihetsep.txt KB317699.1.multihetsep.txt Scaffold_1.multihetsep.txt** 

error in parsing command line: object.Exception@model/data.d(57): Enforcement failed
----------------
??:? pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0x57bb9c]
??:? @safe std.regex.__T10RegexMatchTAxaS453std5regex8internal8thompson15ThompsonMatcherZ.RegexMatch std.exception.enforce!(Exception, std.regex.__T10RegexMatchTAxaS453std5regex8internal8thompson15ThompsonMatcherZ.RegexMatch).enforce(std.regex.__T10RegexMatchTAxaS453std5regex8internal8thompson15ThompsonMatcherZ.RegexMatch, lazy const(char)[], immutable(char)[], ulong) [0x59a7c2]
??:? void model.data.checkDataLine(const(char[])) [0x56a9a1]
??:? ulong model.data.getNrHaplotypesFromFile(immutable(char)[]) [0x56aa92]
??:? void msmc2.parseCommandLine(immutable(char)[][]) [0x5c78a9]
??:? _Dmain [0x5c73bb]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x613553]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x61347b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x6134f8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x61347b]
??:? _d_run_main [0x6133e7]
??:? main [0x5d4bb3]
??:? __libc_start_main [0x3661ed1c]

the first 5 lines of KB317697.1.multihetsep.txt :
KB317698.1      52355   874     CT
KB317698.1      115578  608     GT
KB317698.1      159001  311     GC
KB317698.1      268192  1276    TA
KB317698.1      468419  627     CT

Hope to get your reply.

**Comment by stschiff** [comment]
Is your input file valid? The third column may not contain 0s, and positions need to be increasing.

Stephan

**Comment by yuntwang** [comment]
Hi,
@stschiff 
The problem has been solved.
When I use the following command line:
**msmc2 -t 5 --fixedRecombination -I 0,1 -o msmc_result KB317697.1.multihetsep.txt KB317698.1.multihetsep.txt KB317699.1.multihetsep.txt Scaffold_1.multihetsep.txt**

It can run and I get the final result.
