### ISSUE TITLE
Segfault on your test file in the guide

### ISSUE THREAD

**Issue by fishextinction** [stschiff/msmc#33]
I ran the small 16-snp example file from your guide, and get this on OSX:
```
msmc -t 2 msmc_test.txt 
read 16 SNPs from file msmc_test.txt
estimating scaled mutation rate: 0.00019315
Version:             1.0.1
input files:         ["msmc_test.txt"]
maxIterations:       20
mutationRate:        0.00019315
recombinationRate:   4.82874e-05
subpopLabels:        [0, 0, 0, 0]
timeSegmentPattern:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
nrThreads:           2
nrTtotSegments:      40
verbose:             false
outFilePrefix:       
naiveImplementation: false
hmmStrideWidth:      1000
fixedPopSize:        false
fixedRecombination:  false
initialLambdaVec:    []
directedEmissions:   false
skipAmbiguous:       false
indices:             [0, 1, 2, 3]
logging information written to .log
loop information written to .loop.txt
final results written to .final.txt
[1/1] estimating total branchlengthsSegmentation fault: 11
```

**Comment by stschiff** [comment]
Not sure what the Segfault is about, but it’s not surprising that MSMC doesn’t run on 16 SNPs. You need way more data, and I can imagine heavy overfitting here and zeros in bad places that cause it to blow up.

I will nevertheless try to find out why it blows up exactly.

Stephan

**Comment by fishextinction** [comment]
Thanks. I would gently suggest that it would be great to include a working test dataset so that users can assess whether their copy of the program is working properly.

**Comment by stschiff** [comment]
I agree.
Stephan

**Comment by stschiff** [comment]
I will close this issue. I am currently working on a new guide with actually test data, which will hopefully help users.
