### ISSUE TITLE
running msmc without  final result 

### ISSUE THREAD

**Issue by rxw125** [stschiff/msmc#37]
hi,Stephan, i just started to use msmc . installed the software v1.1.0, found and downloaded the test data from msmc2. but i have been troubled with some problems with simple  command at the begining. My questions are as follows:

###  (1) without final result

cmd：
```
~/msmc-master/build/msmc -R -o EUR_AFR_msmc_output EUR_AFR.chr1.multihetsep.txt
```
log：
read 589382 SNPs from file EUR_AFR.chr1.multihetsep.txt
estimating scaled mutation rate: 0.000451928
Version:             1.1.0
input files:         ["EUR_AFR.chr1.multihetsep.txt"]
maxIterations:       20
mutationRate:        0.000451928
recombinationRate:   0.000112982
subpopLabels:        [0, 0, 0, 0, 0, 0, 0, 0]
timeSegmentPattern:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
nrThreads:           80
nrTtotSegments:      40
verbose:             false
outFilePrefix:       EUR_AFR_msmc_output
naiveImplementation: false
hmmStrideWidth:      1000
fixedPopSize:        false
fixedRecombination:  true
unboundedCrossCoal:  false
initialLambdaVec:    []
loBoundLambda:       0
hiBoundLambda:       inf
directedEmissions:   false
skipAmbiguous:       false
indices:             [0, 1, 2, 3, 4, 5, 6, 7]
logging information written to EUR_AFR_msmc_output.log
loop information written to EUR_AFR_msmc_output.loop.txt
final results written to EUR_AFR_msmc_output.final.txt
[1/1] estimating total branchlengths

### （2） OutOfMemoryError 
   i found the defaults of nrTreads  was too large  and there is one chr（maybe small numbers of SNPs lead to the previous problem）,I  executed  the command as follows :
```  
~/msmc-master/build/msmc -p 10*1 -o EUR_AFR_msmc_output EUR_AFR.chr1.multihetsep.txt -t 2 
```
log:
read 589382 SNPs from file EUR_AFR.chr1.multihetsep.txt
estimating scaled mutation rate: 0.000451928
Version:             1.1.0
input files:         ["EUR_AFR.chr1.multihetsep.txt"]
maxIterations:       20
mutationRate:        0.000451928
recombinationRate:   0.000112982
subpopLabels:        [0, 0, 0, 0, 0, 0, 0, 0]
timeSegmentPattern:  [9220752, 0, 169013428, 1, 140234331517568, 0, 0, 0, 9220752, 0]
nrThreads:           2
nrTtotSegments:      140234518972501
verbose:             false
outFilePrefix:       EUR_AFR_msmc_output
naiveImplementation: false
hmmStrideWidth:      1000
fixedPopSize:        false
fixedRecombination:  false
unboundedCrossCoal:  false
initialLambdaVec:    []
loBoundLambda:       0
hiBoundLambda:       10
directedEmissions:   false
skipAmbiguous:       false
indices:             [0, 1, 2, 3, 4, 5, 6, 7]
logging information written to EUR_AFR_msmc_output.log
loop information written to EUR_AFR_msmc_output.loop.txt
final results written to EUR_AFR_msmc_output.final.txt
core.exception.OutOfMemoryError@src/core/exception.d(700): Memory allocation failed

    
#### I also changed my parameters several  times, but all return the same erro OutOfMemoryError. Could you give me some suggestions? 

Thank you in advance.

**Comment by stschiff** [comment]
Running on 8 haplotypes with Cross-Coalescence rate is like the heaviest you can run with MSMC. MSMC2 is a bit better in that respect. Try running on four haplotypes first, so e.g. by adding `-I 0,1,4,5`.
