### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ChenSh1ne** [stschiff/msmc#38]
$ make -f Makefile 
dmd -debug -O /usr/local/lib/libgsl.a /usr/local/lib/libgslcblas.a -odbuild -ofbuild/msmc model/coalescence_rate.d model/data.d model/emission_rate.d model/gsl_matrix_vector.d model/msmc_hmm.d model/msmc_model.d model/propagation_core.d model/propagation_core_fastImpl.d model/propagation_core_naiveImpl.d model/rate_integrator.d model/stateVec.d model/stateVecAllocator.d model/time_intervals.d model/transition_rate.d model/triple_index.d model/triple_index_marginal.d powell.d brent.d maximization_step.d expectation_step.d msmc.d branchlength.d logger.d
Error: cannot find source code for runtime library file 'object.d'
       dmd might not be correctly installed. Run 'dmd -man' for installation instructions.
Specify path to file 'object.d' with -I switch
make: *** [build/msmc] Error 1

**Comment by stschiff** [comment]
That's a dmd error. You have some paths in your `dmd.conf` set wrongly. Please contact the dmd folks directly, I can't help you there, I'm afraid.
