### ISSUE TITLE
MSMC running with the divergent individuals

### ISSUE THREAD

**Issue by yongzhiyang2012** [stschiff/msmc#39]
Hi Stephan,
I have three individuals from one species, but there divergence time is around 1\~2 million years ago (based on the results of MCMCtree/BEAST inferring with the fossil calibration).
My MSMC result showed a very large _Ne_ in the recent 20~50 kya, is it real? Or just a confused signal by the different population structure? Is there are some methods to test?
Thanks.

**Comment by stschiff** [comment]
What do you mean by divergence time if the three individuals are from one species? Are they from different subpopulations?

The recent high Ne can be an artifact. I would try running with merged time segments in the recent past. You can also try msmc2, which is more stable in the boundaries of the inference time window.
