### ISSUE TITLE
decode time units

### ISSUE THREAD

**Issue by arundurvasula** [stschiff/msmc#41]
Hi Stephan, 

I am running the `decode` program and I was having trouble interpreting the times. 
Here is how I run it:

    ./decode -m 0.0005 -r 0.0004 msmc_input/${SAMPLE}_chr${CHROM}.msmc

Here is the first few lines of output:

```
#time_boundaries:       0       0.0253178       0.0512933       0.0779615       0.105361        0.133531        0.162519        0.192372        0.223144        0.254892        0.287682        0.321584        0.356675        0.393043        0.430783        0.470004        0.510826        0.553385        0.597837        0.644357        0.693147        0.74444 0.798508        0.855666        0.916291        0.980829        1.04982 1.12393 1.20397 1.29098 1.38629 1.49165 1.60944 1.74297 1.89712 2.07944 2.30259 2.59027 2.99573 3.68888 
1902    0.911539        0.0679054       0.00602025      0.00247097      0.00173682      0.00135048      0.00109878      0.000920002     0.000785785     0.000680943     0.000596553     0.000527016     0.000468629     0.000418846     0.000375854     0.000338324     0.000305261     0.000275906     0.000249664     0.000226068     0.000204741     0.000185379     0.000167731     0.00015159      0.000136783     0.000123162     0.000110605     9.9004e-05
      8.82681e-05     7.83175e-05     6.90825e-05     6.05015e-05     5.25191e-05     4.50846e-05     3.81496e-05     3.16647e-05     2.55725e-05     1.97895e-05     1.41384e-05     7.43505e-06     
2902    0.915115        0.0684846       0.00585743      0.00225607      0.00152013      0.00113692      0.000889969     0.000716868     0.000588942     0.000490812     0.000413428     0.000351098     0.000300054     0.000257694     0.000222162     0.000192096     0.000166471     0.000144503     0.000125577     0.000109208     9.50032e-05     8.26449e-05     7.18707e-05     6.24628e-05     5.42383e-05     4.70425e-05     4.07436e-05     3.52282e-05
     3.03982e-05     2.61683e-05     2.24632e-05     1.92165e-05     1.63685e-05     1.38651e-05     1.16558e-05     9.69212e-06     7.92387e-06     6.29146e-06     4.69901e-06     2.68994e-06  
```

Should I scale the times using the 0.0005 mutation rate? i.e. `t/0.0005` to get generations? Or is there a different conversion I should do? Using the genome wide mutation rate of 1.25e-8 gives me coalescent times that are too old to be plausible.

Thanks! 
Arun

**Comment by stschiff** [comment]
Hi Arun, yeah, that's confusing, I agree. The times are scaled by 2N in this case, which is how they are used internally. And N here is simply defined via the heterozygosity. Specifically what you should do is take the parameter `theta` (=2N\mu in my case), which is output in the log file, and divide that by the mutation rate 1.25e-8, which gives you 2N. You then multiply each time value in the decode output by that number. Sorry that this is so confusing, I never really put much effort in the `decode` program.

**Comment by arundurvasula** [comment]
Thanks! Is this log output by the main `msmc` program or in the `decode` program?

**Comment by stschiff** [comment]
I don’t think the decode program has a log output. I mean of the main program.

Stephan
