### ISSUE TITLE
How to install MSMC

### ISSUE THREAD

**Issue by WANGyujian123** [stschiff/msmc#45]
How to install MSMC?  In fact, I can't read the installation instructions. I'm a novice.
Anyone can help???? 
Thanks!!!
I have already installed the GSL, but what's the meaning of  "Adjust the path to the GSL"?
And where is Makefile.linux? Is it in msmc or GSL?
I find Makefile both in msmc and GSL.

**Comment by stschiff** [comment]
Sorry, can't support this. Please seek advice from a sys-admin.
