### ISSUE TITLE
precompiled binaries not working on macOS Catalina

### ISSUE THREAD

**Issue by jssdenton** [stschiff/msmc#47]
When I try running the precompiled binaries on Catalina, I get:

dyld: lazy symbol binding failed: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /Users/jsdenton/Downloads/./msmc_1.1.0
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /Users/jsdenton/Downloads/./msmc_1.1.0
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

A similar issue happens with the precompiled binaries for msmc2:

dyld: lazy symbol binding failed: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /Users/jsdenton/Downloads/./msmc2_macos64bit
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /Users/jsdenton/Downloads/./msmc2_macos64bit
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

**Comment by stschiff** [comment]
Just release a new binary. This should be resolved now. Also for MSMC2
