### ISSUE TITLE
MSMC2- install error

### ISSUE THREAD

**Issue by lwlive** [stschiff/msmc#50]
I  want to install  MSMC2. I have successfuly installed  GSL ( make, make  check  and  make install). However when I  execute 
 "make "  in  msmc2-2.1.3, It reports the foolowing errors:
dmd  -g   -O $(pwd)/gsl-2.6/lib/libgsl.a $(pwd)/gsl-2.6/lib/libgslcblas.a -odbuild/test -ofbuild/release/msmc2 model/data.d model/gsl_matrix_vector.d model/propagation_core.d model/psmc_hmm.d model/psmc_model.d model/stateVec.d model/stateVecAllocator.d model/time_intervals.d model/transition_rate.d powell.d brent.d maximization_step.d expectation_step.d msmc2.d logger.d
$(pwd)/gsl-2.6/lib/libgsl.a(lt86-oper.o): In function `gsl_vector_complex_long_double_div':
oper.c:(.text+0x27a): undefined reference to `hypot'
$(pwd)/gsl-2.6/lib/libgsl.a(lt86-oper.o): In function `gsl_vector_complex_div':
oper.c:(.text+0x7ae): undefined reference to `hypot'
$(pwd)/gsl-2.6/lib/libgsl.a(lt86-oper.o): In function `gsl_vector_complex_float_div':
oper.c:(.text+0xcc2): undefined reference to `hypot'
$(pwd)/gsl-2.6/lib/libgslcblas.a(scnrm2.o): In function `cblas_scnrm2':
scnrm2.c:(.text+0x129): undefined reference to `sqrt'
$(pwd)/gsl-2.6/lib/libgslcblas.a(snrm2.o): In function `cblas_snrm2':
snrm2.c:(.text+0xdb): undefined reference to `sqrt'
$(pwd)/gsl-2.6/lib/libgslcblas.a(srotg.o): In function `cblas_srotg':
srotg.c:(.text+0x15a): undefined reference to `sqrt'
$(pwd)/gsl-2.6/lib/libgslcblas.a(dnrm2.o): In function `cblas_dnrm2':
dnrm2.c:(.text+0xd0): undefined reference to `sqrt'
$(pwd)/gsl-2.6/lib/libgslcblas.a(drotg.o): In function `cblas_drotg':
drotg.c:(.text+0x178): undefined reference to `sqrt'
$(pwd)/gsl-2.6/lib/libgslcblas.a(dznrm2.o):dznrm2.c:(.text+0x11a): more undefined references to `sqrt' follow
collect2: error: ld returned 1 exit status
Error: linker exited with status 1

can you give me some suggestions? or can you offer a binary version？

**Comment by stschiff** [comment]
looks like you have a problem with your GSL install. Can't help there easily I'm afraid.

**Comment by stschiff** [comment]
I will try and provide binaries for all relevant platforms regularly.
