### ISSUE TITLE
msmc is too restrictive WRT chromosome IDs

### ISSUE THREAD

**Issue by mhinsch** [stschiff/msmc#7]
The regexp in line 118 in model/data.d restricts chromosome IDs to regular words (`\w+`). Many file formats, however, allow essentially any non-whitespace character in chromosome or scaffold IDs. A simple change to `\S+` should do the trick.

**Comment by stschiff** [comment]
This is "solved", as I commented out the check altogether. I do enough other checks within the data read function already.
