### ISSUE TITLE
MSMC with genomes in multiple scaffolds, not in chromosomes

### ISSUE THREAD

**Issue by BegonaMartinez** [stschiff/msmc#9]
Hi,
I want to use MSMC with whole genomes which reference genome is in 1140 scaffolds. From your sentence: "MSMC takes as input several files, one for each chromosome" I wonder whether MSMC could still be used for genomes that are not properly grouped into chromosomes. Is it possible? Should I follow the same procedure as if I had chromosomes?
Thank you very much in advance.

BMartinez

**Comment by stschiff** [comment]
Yes, for now you have to put all scaffolds in a separate file. I may implement the (trivial) update to have multiple chromosomes in one file in the future. Note that you should only use scaffolds of reasonable length, say a couple hundred kb long.

**Comment by lwhitacre** [comment]
Hello,
Has MSMC been updated yet to allow for multiple scaffolds in one file? I would also like to use MSMC for a species whose reference genome has not yet been assembled into chromosomes. Because it is in nearly 30,000 pieces putting all the scaffolds in a separate file would be tedious.

Thanks.

**Comment by RCWilliams** [comment]
Hey! Did anybody find a solution to this? I have ~3,000 scaffolds, and using only those larger than a couple hundred kb means using only 5% of my data. I'd really like to use MSMC so if anyone had any suggestions I'd be really grateful! Thanks!

**Comment by stschiff** [comment]
This is still on my to-do list, sorry that I'm slow with it. In the mean time, you could concatenate scaffolds together into Pseudo-Chromosomes, separated by sufficient large chunks of missing data. That way, the Algorithm will effectively add up the likelihoods of the chunks correctly. As spacer, you should use something that sufficiently kills any LD, and the size depends on your recombination rate.
